export const airbnbTheme = {
  borderRadius: "6px",
  borderRadiusLg: "12px",
  button: {
    primary: {
      backgroundColor: "#ff5a5f",
      borderRadius: "6px",
      color: "#ffffff",
      fontSize: "14px",
      fontWeight: "500",
      paddingX: "24px",
      paddingY: "12px",
    },
    secondary: {
      backgroundColor: "transparent",
      border: "1px solid #ff5a5f",
      borderRadius: "6px",
      color: "#ff5a5f",
      fontSize: "14px",
      fontWeight: "500",
      paddingX: "24px",
      paddingY: "12px",
    },
  },
  colorBackground: "#ffffff",
  colorBackgroundMuted: "#fff8f8",
  colorBackgroundSubtle: "#f3f4f6",
  colorBorder: "#e5e7eb",
  colorBorderSubtle: "#f3f4f6",
  colorDanger: "#ef4444",
  colorPrimary: "#ff5a5f",
  colorPrimaryForeground: "#ffffff",
  colorPrimaryHover: "#e04e53",
  colorSuccess: "#10b981",
  colorText: "#111827",
  colorTextMuted: "#6b7280",
  colorTextSubtle: "#9ca3af",
  colorWarning: "#f59e0b",
  containerWidth: "600px",
  fontFamily: '"Circular", "Helvetica Neue", Helvetica, Arial, sans-serif',
  fontFamilyMono: '"Menlo", "Monaco", "Courier New", monospace',
  fontSizeBase: "14px",
  fontSizeHeading: "28px",
  fontSizeLg: "16px",
  fontSizeSm: "12px",
  fontSizeXl: "20px",
  fontWeightBold: "600",
  fontWeightMedium: "500",
  fontWeightNormal: "400",
  lineHeightBase: "1.6",
  spacingBase: "24px",
  spacingLg: "32px",
  spacingXl: "48px",
};
