export const appleTheme = {
  borderRadius: "6px",
  borderRadiusLg: "12px",
  button: {
    primary: {
      backgroundColor: "#0071e3",
      borderRadius: "6px",
      color: "#ffffff",
      fontSize: "14px",
      fontWeight: "500",
      paddingX: "24px",
      paddingY: "12px",
    },
    secondary: {
      backgroundColor: "transparent",
      border: "1px solid #0071e3",
      borderRadius: "6px",
      color: "#0071e3",
      fontSize: "14px",
      fontWeight: "500",
      paddingX: "24px",
      paddingY: "12px",
    },
  },
  colorBackground: "#ffffff",
  colorBackgroundMuted: "#f5f5f7",
  colorBackgroundSubtle: "#f3f4f6",
  colorBorder: "#d2d2d7",
  colorBorderSubtle: "#f3f4f6",
  colorDanger: "#ef4444",
  colorPrimary: "#0071e3",
  colorPrimaryForeground: "#ffffff",
  colorPrimaryHover: "#0077ed",
  colorSuccess: "#10b981",
  colorText: "#1d1d1f",
  colorTextMuted: "#6e6e73",
  colorTextSubtle: "#86868b",
  colorWarning: "#f59e0b",
  containerWidth: "600px",
  fontFamily: '"SF Pro Text", "Helvetica Neue", Helvetica, Arial, sans-serif',
  fontFamilyMono: '"SF Mono", "Menlo", "Monaco", monospace',
  fontSizeBase: "14px",
  fontSizeHeading: "28px",
  fontSizeLg: "16px",
  fontSizeSm: "12px",
  fontSizeXl: "20px",
  fontWeightBold: "600",
  fontWeightMedium: "500",
  fontWeightNormal: "400",
  lineHeightBase: "1.5",
  spacingBase: "24px",
  spacingLg: "32px",
  spacingXl: "48px",
};
