import { defineEmailTheme } from "./define";
import type { EmailThemeTokens } from "./define";

const tokens = {
  borderRadius: "6px",
  borderRadiusLg: "12px",
  button: {
    primary: {
      backgroundColor: "#0061ff",
      borderRadius: "6px",
      color: "#ffffff",
      fontSize: "14px",
      fontWeight: "500",
      paddingX: "24px",
      paddingY: "12px",
    },
    secondary: {
      backgroundColor: "transparent",
      border: "1px solid #0061ff",
      borderRadius: "6px",
      color: "#0061ff",
      fontSize: "14px",
      fontWeight: "500",
      paddingX: "24px",
      paddingY: "12px",
    },
  },
  colorBackground: "#ffffff",
  colorBackgroundMuted: "#f7f8fa",
  colorBackgroundSubtle: "#f3f4f6",
  colorBorder: "#e5e7eb",
  colorBorderSubtle: "#f3f4f6",
  colorDanger: "#ef4444",
  colorPrimary: "#0061ff",
  colorPrimaryForeground: "#ffffff",
  colorPrimaryHover: "#0052dd",
  colorSuccess: "#10b981",
  colorText: "#1f2328",
  colorTextMuted: "#656d77",
  colorTextSubtle: "#9ca3af",
  colorWarning: "#f59e0b",
  containerWidth: "600px",
  fontFamily: '"Inter", "Helvetica Neue", Helvetica, Arial, sans-serif',
  fontFamilyMono: '"SF Mono", "Menlo", "Monaco", monospace',
  fontSizeBase: "14px",
  fontSizeHeading: "28px",
  fontSizeLg: "16px",
  fontSizeSm: "12px",
  fontSizeXl: "20px",
  fontWeightBold: "600",
  fontWeightMedium: "500",
  fontWeightNormal: "400",
  lineHeightBase: "1.5",
  spacingBase: "24px",
  spacingLg: "32px",
  spacingXl: "48px",
} satisfies EmailThemeTokens;

export const dropboxTheme = defineEmailTheme(tokens);
