import { defineEmailTheme } from "./define";
import type { EmailThemeTokens } from "./define";

const tokens = {
  borderRadius: "6px",
  borderRadiusLg: "12px",
  button: {
    primary: {
      backgroundColor: "#ffffff",
      borderRadius: "6px",
      color: "#000000",
      fontSize: "14px",
      fontWeight: "500",
      paddingX: "24px",
      paddingY: "12px",
    },
    secondary: {
      backgroundColor: "transparent",
      border: "1px solid #333333",
      borderRadius: "6px",
      color: "#ffffff",
      fontSize: "14px",
      fontWeight: "500",
      paddingX: "24px",
      paddingY: "12px",
    },
  },
  colorBackground: "#000000",
  colorBackgroundMuted: "#111111",
  colorBackgroundSubtle: "#1a1a1a",
  colorBorder: "#333333",
  colorBorderSubtle: "#1a1a1a",
  colorDanger: "#ef4444",
  colorPrimary: "#ffffff",
  colorPrimaryForeground: "#000000",
  colorPrimaryHover: "#cccccc",
  colorSuccess: "#10b981",
  colorText: "#ffffff",
  colorTextMuted: "#a1a1a1",
  colorTextSubtle: "#6b6b6b",
  colorWarning: "#f59e0b",
  containerWidth: "600px",
  fontFamily: '"Geist", "Inter", -apple-system, sans-serif',
  fontFamilyMono: '"Menlo", "Monaco", "Courier New", monospace',
  fontSizeBase: "14px",
  fontSizeHeading: "28px",
  fontSizeLg: "16px",
  fontSizeSm: "12px",
  fontSizeXl: "20px",
  fontWeightBold: "600",
  fontWeightMedium: "500",
  fontWeightNormal: "400",
  lineHeightBase: "1.6",
  spacingBase: "24px",
  spacingLg: "32px",
  spacingXl: "48px",
} satisfies EmailThemeTokens;

export const vercelTheme = defineEmailTheme(tokens);
